src/carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home


urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from .views import home_page, about_page, contact_page, home_page_one
from accounts.views import login_page, register_page
from api.routes import api_router


urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^home1/$', home_page_one, name='home_1'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(api_router.urls)),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (ProductListView,
                    ProductDetailSlugView,
                    product_list_view
                    )

urlpatterns = [
    url(r'^$', product_list_view, name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
            integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

<!-- Fontawesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/style.css' %}">

src/templates/base/js.html
{% load static %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class="container-fluid" style="max-width:1200px">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img src='{% static "image/Logo.png" %}' width="" height="75" class="d-inline-block align-top" alt="logo">
        <img src='{% static "image/Siemens-logo.png" %}' width="" height="26" class="d-inline-block align-middle" style="margin-top:23px;margin-left:20px" alt="logo">
      </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="narbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav" style="margin:auto;">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                <a href="{{ contact_url }}" class="nav-link">Contact</a>
            </li>
            <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                <a href="{{ product_list_url }}" class="nav-link">Products</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                <a href="{{ logout_url }}" class="nav-link">Logout</a>
            </li>
            {% else %}
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a href="{{ register_url }}" class="nav-link">Register</a>
            </li>
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a href="{{ login_url }}" class="nav-link">Login</a>
            </li>
            {% endif %}
            <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                <a href="{{ cart_url }}" class="nav-link">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
            </li>
        </ul>
        {% include 'search/snippets/search-form.html' %}
    </div>
        </div>
</nav>