src/carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home


urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from .views import home_page, about_page, contact_page, home_page_one
from accounts.views import login_page, register_page
from api.routes import api_router


urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^home1/$', home_page_one, name='home_1'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(api_router.urls)),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            print('Cart Id Exists')
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    products    = models.ManyToManyField(Product, blank=True)
    user        = models.ForeignKey(User, null=True, blank=True)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    sub_total   = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, action, instance, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.sub_total > 0:
        instance.total = instance.sub_total
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect
from .models import Cart
from django.contrib import messages
from products.models import Product
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    product_obj = ''
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Product not found :(. Go back to <a href="/products/">Products</a>! ')
            return redirect('cart:home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            messages.add_message(request, messages.SUCCESS,
                                 'Product removed from <a href="/cart/">Cart</a>!')
        else:
            cart_obj.products.add(product_obj)
            messages.add_message(request, messages.SUCCESS,
                                 'Product added to <a href="/cart/">Cart</a>!')
        request.session['cart_items'] = cart_obj.products.count()
    # cart_obj.products.remove(product_obj)
    # return redirect(product_obj.get_absolute_url())
    return redirect('cart:home')


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    user = request
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()

    if request.user.is_authenticated():
        if request.user.email:
            billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(
                user=request.user,
                email=request.user.email,
            )
            print(request.user.email)

    context = {
        "object": new_order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form
    }

    return render(request, "carts/checkout.html", context)

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}


{% if not billing_profile %}

<div class="row text-center">
    <div class="col-12 col-md-6">
        <p class="lead">login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class="col-12 col-md-6">
        Continue as Guest
    </div>
</div>



{% else %}
    <h1>Checkout</h1>

    <p>Cart Total: {{object.cart.total}}</p>
    <p>Shipping Total: {{ object.shipping_total }}</p>
    <p>Order Total: {{ object.total }}</p>
{% endif %}

{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
          <strong>{{message|safe}}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endfor %}
{% endif %}

<h1>Cart</h1>

{% if cart.products.exists %}
<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Product Name</th>
            <th>Product Price</th>
        </tr>
    </thead>
    <tbody>
    {% for product in cart.products.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>

                {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}</td>
            <td>{{ product.price }}</td>
        </tr>
    {% endfor %}
        <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b> {{cart.sub_total}}</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td><b>total</b> {{cart.total}}</td>
        </tr>

        <tr>
            <td colspan="2"></td>
            <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
        </tr>

    </tbody>
</table>
{% else %}
    <p class="lead">Cart is empty</p>
{% endif %}

{% endblock %}